---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: c55121348430c2fa33cf2285d96a8f9836ce9fec # HEAD as of 12.01.2020
requirements_git_track_branch: master


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: b54455f165a7fe61ddda695c8560fec88ce47fea  # HEAD as of 12.01.2020
aodh_git_project_group: aodh_all
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: c38513224edc7872c0242ce26c6a93080b614e3a  # HEAD as of 12.01.2020
barbican_git_project_group: barbican_all
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 0c0948f0a7ae292b90c8878a41e107f5de4e8000  # HEAD as of 12.01.2020
ceilometer_git_project_group: all
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: bcc2539071d5239159cd46013e1af3eb2dc478e9  # HEAD as of 12.01.2020
cinder_git_project_group: cinder_all
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 0050549441a1889a40b85accc4733d3dca8f067f  # HEAD as of 12.01.2020
designate_git_project_group: designate_all
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: b194e71909846b1c9acce4995ce8fd05356c3b4d  # HEAD as of 12.01.2020
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 2291fe673ec2f875bfc4c49e8ee487c074f1b027  # HEAD as of 12.01.2020
glance_git_project_group: glance_all
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 7b65b78c95f9c6177df1f6bbef4a55aa055ee030  # HEAD as of 12.01.2020
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 994eeb58f9005c19eb8664b8829e7aa167c2b946  # HEAD as of 12.01.2020
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: aa3c7e1919c921289a5ae4b7f0c582ab7065c01c  # HEAD as of 12.01.2020
horizon_git_project_group: horizon_all
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 31234a301dd69a581ed414ec12606e769bbadc72  # HEAD as of 12.01.2020
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 5623ab2e03ebd1c7a46a70a739e8b6b0ac7f296b  # HEAD as of 12.01.2020
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: dbc0a4aaf1fe4a4c7b0dd5f350d8f05380f80888  # HEAD as of 12.01.2020
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: master

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: d017b824feaef6381bfff7d6a7ff8a8a2d36f11d  # HEAD as of 12.01.2020
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: bfce75ee8cf041f59942255c858a7c5588d27b2f # HEAD as of 12.01.2020
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 28a1da6c74e7b665a0024ee0574cce916df4584d  # HEAD as of 12.01.2020
keystone_git_project_group: keystone_all
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: cc729152ecdc1cbeea56753e3b1c88a75e3928c1  # HEAD as of 12.01.2020
manila_git_project_group: manila_all
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: ae67ae824ce38da158777ad6bd9a23e1088b115a  # HEAD as of 12.01.2020
neutron_git_project_group: neutron_all
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 4a1ebf6d0ac9d6c55d4e347ddf00298e6a60ce8f  # HEAD as of 12.01.2020
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: f51b47506288679e9745c625ca765a2c7795239f  # HEAD as of 12.01.2020
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 777fb1638e8b3d15ca261dfe449b443381819509  # HEAD as of 12.01.2020
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://opendev.org/openstack/networking-calico
networking_calico_git_install_branch: 3.11.1  # HEAD as of 12.01.2020
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: None

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 358da8623ad8cb8df40f2a93cea64c3ce66305db  # HEAD as of 12.01.2020
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: master

networking_ovn_git_repo: https://opendev.org/openstack/networking-ovn
networking_ovn_git_install_branch: eda5d7f80d877601170631c5f5485370ea701f42  # HEAD as of 12.01.2020
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: master

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "master" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 84175687fb5c23fdf76322b18392c783ca8d6d73  # HEAD as of 12.01.2020
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: master


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 67d9b5114e0044ea1135d1797241e883e7646646  # HEAD as of 12.01.2020
nova_git_project_group: nova_all
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: bb2f1f586b6558367d0810e60c27e36195b48609 # HEAD as of 12.01.2020
sahara_git_project_group: sahara_all
sahara_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: a4f10788648df60d43992738a30509ce12a64f66 # HEAD as of 12.01.2020
swift_git_project_group: swift_all
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 13e350c7ad7abc1cd267e40790fb122726a71187  # HEAD as of 12.01.2020
ironic_git_project_group: ironic_all
ironic_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: c681b88f71eb45d0cc2b96b0d6ecbe8ca5c8f34e  # HEAD as of 12.01.2020
magnum_git_project_group: magnum_all
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 596b3d142eeea935fb2293de5631cd9dd4c191c6  # HEAD as of 12.01.2020
masakari_git_project_group: masakari_api
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: b717be163e96dfd7363885a937f05197be3530b1  # HEAD as of 12.01.2020
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: fef538cce793518f4e7bfe645f0ccbd6dc55ad0a  # HEAD as of 12.01.2020
mistral_git_project_group: mistral_all
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: b33d398950993cbf2e73e767eade281d67cd8546  # HEAD as of 12.01.2020
murano_git_project_group: murano_all
murano_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: a5f6c9b82ceee093b3e2fcb71ca8db102cabe452 # HEAD as of 12.01.2020
trove_git_project_group: trove_all
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: d38aa6140a4710fee4ca572732bf59fdbee9f836 # HEAD as of 12.01.2020
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 47e0ef31bcfd34838fac4c619b699edd65e20223  # HEAD as of 12.01.2020
octavia_git_project_group: octavia_all
octavia_git_track_branch: master


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: f7f87fc9694ccaff5e8dc149f956679676210d09  # HEAD as of 12.01.2020
panko_git_project_group: panko_all
panko_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 4e58f8a56b1f78f8ab2f96fb6c8e64e88c651fc3  # HEAD as of 12.01.2020
placement_git_project_group: placement_all
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: c3263b83da705e089f98d0fce44feb7f137c5105 # HEAD as of 12.01.2020
tacker_git_project_group: tacker_all
tacker_git_track_branch: master


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: 7aa9e87eaff8f8946d453ee6f9ed4ef5776c8196  # HEAD as of 12.01.2020
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 2fd7d6ede223fcff626cea0f9ff2091f72986f75  # HEAD as of 12.01.2020
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: b0b6e78ad39313710c300627a08bf6770cb4e221  # HEAD as of 12.01.2020
blazar_git_project_group: blazar_all
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 9f030ebc27572909b9315f1a6dd88f36c00ae72c  # HEAD as of 12.01.2020
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: master
